"""Model methods

Revision ID: 2d685089ae35
Revises: cbae24c73896
Create Date: 2023-11-09 14:05:28.750124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d685089ae35'
down_revision = 'cbae24c73896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
