"""Relationship update

Revision ID: 92d116b96ce5
Revises: 988665954ced
Create Date: 2023-11-09 13:28:06.652016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d116b96ce5'
down_revision = '988665954ced'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
