"""Relationship update

Revision ID: cbae24c73896
Revises: 92d116b96ce5
Create Date: 2023-11-09 13:39:22.988978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbae24c73896'
down_revision = '92d116b96ce5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
